apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-filer
  namespace: seaweedfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-volume2
  resources:
    requests:
      storage: 10Gi
