apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo.tempo.svc:3100
    isDefault: false
    jsonData:
      timeout: "60"
      tracesToLogsV2:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: mimir
