---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgASLLZxp/gdCFy8PRmZr5NQ58lD+ZgwomGKf+wM12VRco1pxIex7T0+039ShTgxEvcQmGEyTGcPtZOWcmsdKx6HpxsNzllx5SrYzBi+8aNIEjZGu6/NtXQ6doHgISTHVpzeaVWGNHpiiHuxu6rLzo7jI9vfjjPVFSd4lVP/erCNO9PQ1ylIf+OrAjptZeCFP49b+onsIMxsfmEznzSTMaectgACto05hGDJ8G8G/3H56N9W6XG75ccug/WA6QlKuR4ggG/CCfsFR4QNUXh9ldpa6CkdsAJORlpHXaWuPjS8Lwc9ihPkmYdTQIvj2Igg8WqWzf6iEIRK0cKlmYB8qXhIVDH3xraN+EbakyLHYzbmM0aRJkZgVMtLBhc8+UHzK38+jTwfIGMrjJrrd0tMPEILMLdXGwiGFGjdPtDeGsQqjoI8yiPI9netLAJKfYH5qcRTIOhdHYcEqztXfGi3AGTbKe4MPakgKd1wqDZMpbmvphPgKNTXbZClwrVtIjXoG8yHJ8VFD5MTftnSYPdM/rd4uRn2xrhAyHcaaXfcChMYa+lb0eD+HckNUxtAMUw2kycQtghkcoiW8ydjscuJGVMvqFUEklE0WDJHidhjd3YLgKSz4XST7pbL2UgpXipdftV/9GPU/MeY2ZXaavaiHBg1Xs/HBaFNr1CWL80SHNhpOHkHf94RRE7MUT7PSpt4il3pG+gmviLt28bpEE1XMg/BQ9rw53J50+lBK+Yk4OZoWFxMBSr3jtOKyvu0175EKlfAyug00eyPsWkhjhg17QErzr6fz4m3q0WM9FgU112DdgGfCAsDMbMuX8UChORC0h0vCw7xZTTpoTdy6bii0z+5byd3ZgWDFaPy83OIY+LWH3IXubNn0JVOX50=
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
