---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgA71hgenCEaySysZFFmMQnwdpVFRDdyrpwGzkCbAfd//3lIaZkSTyvUbyqgyQ9vLGuLzZqd+3DlU0nmtr2mydZ8IMTu6nbMEtaDt3+07Ln9fKfVoufxy2afTFyrKyZFxVCsEwT2l5SwInv/gmBaUi3RQ9mQ5eQFj+puTGtOWwCqSG+B8ACo/YGptWxbSX2SOFOzuzwkrsPGFNaf96+bNbI74lXOqe6fT9D4IOB3oAnA5tEoVzdHTpKrhHpKvhmsYBLWt+j+LmSSHBxmuC9c6PhhZRu7TcFYaC8F5g4AZoLSEgYGpXtOc4J1OausloxYc3dC7h3DxLtpFA/mj/aVveVNDVnT7qVPFxHBXBWkKqsi8HAzHWM1+q6Jqg1aNBte5AmpMx78XP4gjddI5hOnfqk+6zIuIqI0V6IptgY1TnK1e3fAS/DjzYXGO/49HVG9/PxDJixl485qPRJK2/1sJaoZ4E2xKWvQnW5FNT+FbpStv/Im9X7t3teOtlY67HJoM3x9IUmgXx9/uer3brzIaTH58qxyxUVvjxw+SQgRAG6dSepekuscFJp7xOwWnwTJC5CC2cPRl4K3YyIKdALbKwjQWts/lAEmlW66nwV0uG+CMq8NH0d7GtCcaQgUkDnXXf8GAve5zilIWdWWgUUdwkh8L9u1lkQ/TLTdSI3+db6vqdIhk8MhiXmC53D3GwBbnqzwkJjfeRWob0tXZJWNHEnwLvXLY3GYggsqk5axBT4dE+/B1+tBMXbZTAK+TuTDV+hsJhK56RzIxdn0MjNmIGLl49u1N1XajKVd3efv7wfBojT0AOH8Zpw08ZC44ETNPCfgtXViuJkjHJKg5rygAgyHC+xlCuGgS5uj1docDTWcvRNIAYYLqXxcjA==
  template:
    metadata:
      name: client-info-secret
      namespace: synology-csi
