{
 "title": "Minecraft Fabric (Public)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"})"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\",area=\"heap\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"})"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}) by (world)",
     "legendFormat": "Players in {{world}}"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Tick Duration",
   "type": "timeseries",
   "description": "The duration required to compute each tick. 50 milliseconds per tick = 20 ticks per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_mspt{type!=\"max\",instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}",
     "legendFormat": "{{type}} MSPT"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(minecraft_entities{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Entities by spawn group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}) by (world)",
     "legendFormat": "Entities in {{world}}"
    }
   ]
  },
  {
   "title": "Process CPU Time in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_loaded_chunks{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}) by (world)",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "JVM GC Duration",
   "type": "timeseries",
   "description": "Time spent in a given JVM garbage collector in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"jvm_gc_collection_seconds_sum\",instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate({__name__=\"jvm_memory_pool_bytes_used\",instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}[10m])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "timeseries",
   "description": "Current count of threads by state",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_state{instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}) by (state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_threads_(current|daemon|peak|deadlocked|deadlocked_monitor)\",instance=\"minecraft.minecraft.svc:25585\",job=\"minecraft-fabric\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}