{
 "title": "SeaweedFS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(SeaweedFS_build_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Filer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filer Request Duration 90th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "seaweedfs:filer_request_duration:p90{cluster=\"$cluster\"}",
       "legendFormat": "average"
      },
      {
       "expr": "seaweedfs:filer_request_duration_by_type:p90{cluster=\"$cluster\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer Request Duration 95th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "seaweedfs:filer_request_duration:p95{cluster=\"$cluster\"}",
       "legendFormat": "average"
      },
      {
       "expr": "seaweedfs:filer_request_duration_by_type:p95{cluster=\"$cluster\"}",
       "legendFormat": "{{type}}"
      },
      {}
     ]
    },
    {
     "title": "Filer Request Duration 99th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "seaweedfs:filer_request_duration:p99{cluster=\"$cluster\"}",
       "legendFormat": "average"
      },
      {
       "expr": "seaweedfs:filer_request_duration_by_type:p99{cluster=\"$cluster\"}",
       "legendFormat": "{{type}}"
      },
      {}
     ]
    },
    {
     "title": "Filer QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(SeaweedFS_filerStore_request_total{cluster=\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Filer Concurrent Uploads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SeaweedFS_filer_in_flight_upload_count{cluster=\"$cluster\"}",
       "legendFormat": "uploads"
      }
     ]
    },
    {
     "title": "Filer Concurrent Upload Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "SeaweedFS_filer_in_flight_upload_bytes{cluster=\"$cluster\"}",
       "legendFormat": "bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "panels": [
    {
     "title": "S3 Concurrent Uploads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "SeaweedFS_s3_in_flight_upload_count{cluster=\"$cluster\"}",
       "legendFormat": "uploads"
      }
     ]
    },
    {
     "title": "S3 Concurrent Upload Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "SeaweedFS_s3_in_flight_upload_bytes{cluster=\"$cluster\"}",
       "legendFormat": "bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Request Duration 50th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "seaweedfs:s3_request_duration:p50{cluster=\"$cluster\"}",
     "legendFormat": "average"
    },
    {
     "expr": "seaweedfs:s3_request_duration_by_type_bucket:p50{cluster=\"$cluster\"}",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 95th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "seaweedfs:s3_request_duration:p95{cluster=\"$cluster\"}",
     "legendFormat": "average"
    },
    {
     "expr": "seaweedfs:s3_request_duration_by_type_bucket:p95{cluster=\"$cluster\"}",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "seaweedfs:s3_request_duration:p99{cluster=\"$cluster\"}",
     "legendFormat": "average"
    },
    {
     "expr": "seaweedfs:s3_request_duration_by_type_bucket:p99{cluster=\"$cluster\"}",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Traffic Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_s3_bucket_traffic_received_bytes_total{cluster=\"$cluster\"}[$__interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Traffic Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_s3_bucket_traffic_sent_bytes_total{cluster=\"$cluster\"}[$__interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 API Calls per Bucket",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_s3_request_total{cluster=\"$cluster\"}[$__interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 API QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(SeaweedFS_s3_request_total{cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 API Monthly Cost if on AWS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Cost in US$" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (increase(SeaweedFS_s3_request_total{cluster=\"$cluster\", type=~'PUT|COPY|POST|LIST'}[$__range]))*0.000005",
     "legendFormat": "{{type}} requests"
    },
    {
     "expr": "sum(increase(SeaweedFS_s3_request_total{cluster=\"$cluster\", type=~'PUT|COPY|POST|LIST'}[$__range]))*0.000005",
     "legendFormat": "All PUT, COPY, POST, LIST"
    },
    {
     "expr": "sum (increase(SeaweedFS_s3_request_total{cluster=\"$cluster\", type!~'PUT|COPY|POST|LIST'}[$__range]))*0.0000004",
     "legendFormat": "GET and all other"
    },
    {
     "expr": "sum by (type) (increase(SeaweedFS_s3_request_total{cluster=\"$cluster\", type!~'PUT|COPY|POST|LIST'}[$__range]))*0.0000004",
     "legendFormat": "{{type}} requests"
    }
   ]
  },
  { "title": "Volume Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Volume Server Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "seaweedfs:volume_request_duration_by_instance:p99{cluster=\"$cluster\"}",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "seaweedfs:volume_request_duration:p99{cluster=\"$cluster\"}",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Volume Server QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_volumeServer_request_total{cluster=\"$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_volumes{cluster=\"$cluster\"}) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_max_volumes{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Collection and Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size{cluster=\"$cluster\"}) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size{cluster=\"$cluster\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Filer Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Filer Store Request Duration 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "seaweedfs:filer_request_duration_by_type:p99{cluster=\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Store QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_filerStore_request_total{cluster=\"$cluster\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Filer Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Filer Go Memory Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"seaweedfs-filer\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"seaweedfs-filer\"}[$__rate_interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"seaweedfs-filer\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"seaweedfs-filer\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Filer Go GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"seaweedfs-filer\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Filer Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"seaweedfs-filer\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"seaweedfs-filer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "resident {{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"seaweedfs-filer\"}",
     "legendFormat": "virtual {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"seaweedfs-filer\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_max_fds{job=\"seaweedfs-filer\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "S3 Bucket Object Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(SeaweedFS_s3_bucket_object_count{cluster=\"$cluster\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Size (Logical)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(SeaweedFS_s3_bucket_size_bytes{cluster=\"$cluster\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Size (Physical)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(SeaweedFS_s3_bucket_physical_size_bytes{cluster=\"$cluster\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}