apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: grafana
spec:
  encryptedData:
    url: AgB9JP78a72xvXEnCN+yCY6w6jknCbSnh3cck0mP/Sr6/w4oanZFIt7BMiaQy/dLcYWDKAuLGkd5b4nKlDfG6z2+tsiszcJkBJP+bcDYG1CWqaaxo5qfqN60KjkxO6CitJfqFcimSCs/DV/YcijHELlUEuSX2UFWc3lcB6qzseErnYjzqgezFNRZyeNrkcmU9rE334b1xwceDqmFGAfZhvDJjN8QZI4JXE8MgintKjxO9YFG03eQa/4mFiGNHclGuZfX60npyiDopZaNA+ianRFzmiSml9ODNKBFkD7FCigXnw0BLRZDkkYge2D4oPPlxeVEuRy6yaM7HRPgduk2eeToydQbQE91QeLi6ERf4vlg0B1ad0HzoiLV5lrjKihoMgnArY+FxuQd1TqL6U3UDyodW4UlJCFbgDhTbgc+Ibds/EP3JUkUELfPQlBi9Unw2+rogWiTcdbzO6v1UwxFUJhaktXLRW6kdwWo8/bWsd1+THeujOzsT2omBcqaVAMsW8sEob3kD+xS45pB8BSVM+35UCly38SGJ+szfon8fh2tiz4ruDgNOE8nwwNuK/N0XYZw3I0DRt1Gm/eGXrhgF2/0RYrw7BQOsFT2RL567Iyxmx9EM7r57DJPyyIdRcQUwHUY2ImDRS3V8lwqlk1/9x5CrVZ30SIu5dDSykjzklglvlmiilw0yEUVZ03AOWC1KcAIIAsRvjOW93nr0SwsYTTo0SP8l9QxDqxtWeIY72XMIOmYixCL1nf1i+3c6qynbf9cM1VVYvlzODPL/iDRtQjECdLXMJYNI2e9gmz6cVRzi9ViPf2qh+xeZK80E9bq7KLha7xJ4rrQN7fAnWQ3+hLRzFjvVAq4vnQE
  template:
    metadata:
      name: discord-webhook
      namespace: grafana
