apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      mode: console
    auth:
      disable_login_form: "false"
    server:
      root_url: https://grafana.yhmd.dev
    unified_alerting:
      enabled: "true"
    alerting:
      enabled: "false"
    rendering:
      server_url: http://localhost:8081/render
      callback_url: http://localhost:3000
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: image-renderer
              image: grafana/grafana-image-renderer:latest
              env:
                - name: BROWSER_READINESS_TIMEOUT
                  value: "120s"
              resources:
                requests:
                  memory: "512Mi"
                limits:
                  memory: "2Gi"
