apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: dashboard-renderer
  namespace: grafana
spec:
  name: dashboard-renderer
  role: Viewer
  instanceName: grafana
  tokens:
    - name: renderer-token
      secretName: grafana-renderer-token
