---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paseo-secrets
  namespace: paseo
spec:
  encryptedData:
    PASEO_PASSWORD: AgA5ohGzgvDQb3qkzCFkO71BzGwmDy2lkeNeZk3s4c+FjHl+3twmBCG0ham16LjiZo6as6lQuNpSDtMShxHrIxKU7Qi5Fdkyb44y/7QKC/F9z6qfAh/fmR3+xe9FOoRrtnotgFJ6YB0/+ubmsgrd8f869L1AaPIiWOKWiz8qgnjHJp4yM68ajrVFFwQ/AmkmnApqW6jcaPCUrccWIgI5fWbXjEGLoiSTvsw5PZcdgVbBkoyYzA0jM6xhhvwLbB9jB606WGNSJwqvXloku5bDs3+L3uzdrWoJrW3ndIaf7m+w7MH4/78MJTd62b16V1OfuxcqiJaMRBu77TCvVBU/7jsAoSfYTO0qv1sfpWyoYeCBEjuDjgOrW6JqHtAC2kR2ctdiWA9BBveY9L23SXicD592D5vXC/Fo9/0zisQBf5ffA5nghLNv9lqtTktosR2pqPf2IZTcvwn8QKSKROJG/Tijhp0MMDGw5hZWr/87/ukt+Z21COTbJ7VWEgDlYg/EIfMo1HyMfCBuDGAtYNAH2l13+g6Gf4mvHZ6drj02quxJswtn8Oh5HXTSjf9QeZqwgM+2DE3ESBlYPg2s5f57iqAcSFFyTts2U+NYWH00FGg8WMzffxT/bDFQcByB7/jcrYz4vZ4ly6Ix5uPa9Sy0QknvxJgz0TXgylquhCuX89UneOeoqj9kfaWhfr0MPR2kuV+sKgv/aGwJ2usEO+lWLYssosoRScU2LKwg6OcoeV+pqw==
  template:
    metadata:
      name: paseo-secrets
      namespace: paseo
